# Seed 15 Data
name: 'webq_seed_15'
data_dir: '../data/WebQ_entclf_delex_seed_15_fullvocab_plus/'
train_data: 'train_vec_notime.json'
valid_data: 'valid_vec_notime.json'
test_data: 'test_vec_notime.json'
pre_word2vec: '../data/WebQ_entclf_delex_seed_15_fullvocab_plus/glove_pretrained_300d_w2v.npy'

# Full vocab
vocab_size: 100797
num_ent_types: 1712
num_relations: 4996

num_query_words: 10

# Output
model_file: '../runs/WebQ_entclf/best/bamnet_seed_15_fullvocab_delex_plus_notime_0.557.md'

# Model
query_size: 32
query_markup_size: 1 # Not used
ans_bow_size: 1 # Not used
ans_path_bow_size: null
ans_ctx_entity_bow_size: 6

vocab_embed_size: 300
hidden_size: 128
o_embed_size: 128
mem_size: 96
word_emb_dropout: 0.3
que_enc_dropout: 0.3
ans_enc_dropout: 0.2
attention: 'add'
num_hops: 1

# Training
learning_rate: 0.001
batch_size: 32
num_epochs: 100
valid_patience: 10
margin: 1

# Testing
test_batch_size: 1
test_margin:
        - 0.7

# Device
no_cuda: False
gpu: 0
